/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-11-22 07:17:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=emulateIE7\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/WdatePicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/skin_/form.css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/umeditor/themes/default/_css/umeditor.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/global.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.select.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/WdatePicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.UMEDITOR_HOME_URL = 'umeditor/';  // 请换成绝对路径\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/umeditor.config.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/editor_api.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/umeditor/lang/zh-cn/zh-cn.js\"></script>\r\n");
      out.write("<title>基础信息</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t<div id=\"hd\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"bd\">\r\n");
      out.write("    \t<div id=\"main\">\r\n");
      out.write("            <h2 class=\"subfild\">\r\n");
      out.write("            \t<span>基本信息</span>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <div class=\"subfild-content base-info\">\r\n");
      out.write("            \t<div class=\"kv-item ue-clear\">\r\n");
      out.write("                \t<label><span class=\"impInfo\">*</span>文章标题</label>\r\n");
      out.write("                \t<div class=\"kv-item-content\">\r\n");
      out.write("                    \t<input type=\"text\" placeholder=\"文章标题\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"kv-item-tip\">标题字数限制在35个字符</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"kv-item ue-clear time\">\r\n");
      out.write("                \t<label><span class=\"impInfo\">*</span>发布时间</label>\r\n");
      out.write("                \t<div class=\"kv-item-content\">\r\n");
      out.write("                    \t<input type=\"text\" placeholder=\"文章标题\" onfocus=\"WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})\" />\r\n");
      out.write("                        <i class=\"time-icon\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"kv-item-tip error\">这是一个错误信息</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"kv-item ue-clear\">\r\n");
      out.write("                \t<label>所在栏目</label>\r\n");
      out.write("                \t<div class=\"kv-item-content\">\r\n");
      out.write("                    \t<select>\r\n");
      out.write("                        \t<option>新闻资讯</option>\r\n");
      out.write("                            <option>新闻资讯</option>\r\n");
      out.write("                            <option>新闻资讯</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"kv-item-tip success\">成功信息</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"kv-item ue-clear\">\r\n");
      out.write("                \t<label>是否审核</label>\r\n");
      out.write("                \t<div class=\"kv-item-content\">\r\n");
      out.write("                    \t<span class=\"choose\">\r\n");
      out.write("                            <span class=\"checkboxouter\">\r\n");
      out.write("                                <input type=\"radio\" name=\"need\" />\r\n");
      out.write("                                <span class=\"radio\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span class=\"text\">是</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    \t<span class=\"choose\">\r\n");
      out.write("                            <span class=\"checkboxouter\">\r\n");
      out.write("                                <input type=\"radio\" name=\"need\" />\r\n");
      out.write("                                <span class=\"radio\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <span class=\"text\">否</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"kv-item-tip\">标题字数限制在35个字符</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"kv-item ue-clear\">\r\n");
      out.write("                \t<label><span class=\"impInfo\">*</span>缩略图</label>\r\n");
      out.write("                \t<div class=\"kv-item-content file\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text\"></span>\r\n");
      out.write("                        <input type=\"file\" />\r\n");
      out.write("                        <input type=\"button\" class=\"button normal long2\" value=\"浏览..\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"kv-item-tip\">标题字数限制在35个字符</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <h2 class=\"subfild\">\r\n");
      out.write("            \t<span>备注资料</span>\r\n");
      out.write("            </h2>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"subfild-content remarkes-info\">\r\n");
      out.write("            \t<div class=\"kv-item ue-clear\">\r\n");
      out.write("                \t<label><span class=\"impInfo\">*</span>文章内容</label>\r\n");
      out.write("                \t<div class=\"kv-item-content\">\r\n");
      out.write("                    \t<textarea placeholder=\"文章内容\" id=\"content\" style=\"width:800px;height:240px;\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"buttons\">\r\n");
      out.write("                <input class=\"button\" type=\"button\" value=\"确认修改\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$('select').select();\r\n");
      out.write("\tshowRemind('input[type=text],textarea','color5');\r\n");
      out.write("\tUM.getEditor('content');\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
